services:
  web1:
    build: .
    container_name: securebox-web1
    ports:
      - "2221:22"
      - "8082:80"
      - "8443:443"

  web2:
    build: .
    container_name: securebox-web2
    ports:
      - "2222:22"
      - "8083:80"
      - "8444:443"

  db1:
    build: .
    container_name: securebox-db1
    ports:
      - "2223:22"
      - "3307:3306"
